server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          default-label: dev1
          uri: https://github.com/bryanjesuscastro2003/fastPaymentV2
          search-paths: config-data